name = "cf-img"
type = "rust"
main = "build/worker/shim.mjs"
compatibility_date = "2024-08-12"
account_id = "0f78629c87903f0a0efdf9c2608cce3d"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[kv_namespaces]]
binding = "redis"
id = "82d23b305f784ac7bea02178ece6b76a"

[placement]
mode = "smart"